interface Int32Array {
    // Missing from WebCore??
    void set(in Int32Array array, in [Optional] unsigned long offset);
    void set(in sequence<long> array, in [Optional] unsigned long offset);
};
