interface Uint32Array {
    // Missing from WebCore??
    void set(in Uint32Array array, in [Optional] unsigned long offset);
    void set(in sequence<long> array, in [Optional] unsigned long offset);
};
