interface Uint8Array {
    // Missing from WebCore??
    void set(in Uint8Array array, in [Optional] unsigned long offset);
    void set(in sequence<long> array, in [Optional] unsigned long offset);
};
